{{- include "sch.config.init" (list . "apps.sch.chart.config.values") -}}
{{- if not (and .Values.hookServiceAccountName .Values.ltpaKeys.secretName) }}
---
###############################################################################
# © Merative US L.P. 2022,2025
# Copyright 2019,2020 IBM Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
###############################################################################

apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "sch.names.fullCompName" (list . "secret-manager") }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "sch.metadata.labels.standard" (list . "hook") | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade,post-delete
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation
imagePullSecrets:
  {{- if or .Values.global.imagePullSecret.secretName .Values.global.imagePullSecret.username }}
  - name: {{ default (printf "%s-hook-pullsecret" .Release.Name) .Values.global.imagePullSecret.secretName }}
  {{- end }}
  {{- if or .Values.global.hubPullSecret.secretName .Values.global.hubPullSecret.username }}
  - name: {{ default (printf "%s-hook-hubsecret" .Release.Name) .Values.global.hubPullSecret.secretName }}
  {{- end }}

{{- end }}
