{{- include "sch.config.init" (list . "apps.sch.chart.config.values") -}}
{{- if not .Values.wlpAdmin.secretName }}
---
###############################################################################
# © Merative US L.P. 2022,2025
# Copyright 2019,2020 IBM Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
###############################################################################

apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ .Release.Name }}-wlpadm
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "sch.metadata.labels.standard" (list . "hook-wlpadm") | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": before-hook-creation
data:
  # Password for the WebSphere Liberty keystore
  KeystorePassword: {{ randAlphaNum 15 | b64enc}}
  # Username for the WebSphere Liberty administrative account
  WebSphereUsername: {{ b64enc "websphere" }}
  # Password for the WebSphere Liberty administrative account
  WebSpherePassword: {{ randAlphaNum 15 | b64enc}}
{{- end }}
