{{- include "sch.config.init" (list . "apps.sch.chart.config.values") -}}
---
###############################################################################
# © Merative US L.P. 2022,2025
# Copyright 2020 IBM Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
###############################################################################

apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "sch.names.fullCompName" (list . "delete-generated") }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "sch.metadata.labels.standard" (list . "delete-generated-hook") | nindent 4 }}
  annotations:
    "helm.sh/hook": post-delete
    "helm.sh/hook-weight": "5"
    "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation
spec:
  backoffLimit: 1
  template:
    metadata:
      labels:
        {{- include "sch.metadata.labels.standard" (list . "delete-generated-hook") | nindent 8 }}
    spec:
      restartPolicy: Never
      {{- include "sch.security.securityContext" (list . .sch.chart.podSecurityContext) | nindent 6 }}
      affinity:
        {{- include "sch.affinity.nodeAffinity" (list . .sch.chart.nodeAffinity) | nindent 8 }}
      serviceAccountName: {{ default (include "sch.names.fullCompName" (list . "secret-manager")) .Values.hookServiceAccountName }}
      containers:
        - name: delete-generated
          image: bitnami/kubectl:{{ .Capabilities.KubeVersion.Major }}.{{ trunc 2 .Capabilities.KubeVersion.Minor }}
          command:
            - /bin/sh
            - -c
          args:
            - |
              /opt/bitnami/kubectl/bin/kubectl delete job {{ include "sch.names.fullCompName" (list . "apply-customsql") }} --ignore-not-found;
              /opt/bitnami/kubectl/bin/kubectl delete configmap {{ include "sch.names.fullCompName" (list . "hook-bootstrap") }} --ignore-not-found;
              /opt/bitnami/kubectl/bin/kubectl delete configmap {{ include "sch.names.fullCompName" (list . "hook-customsql") }} --ignore-not-found;
              /opt/bitnami/kubectl/bin/kubectl delete secret {{ include "sch.names.fullCompName" (list . "hook-dbcreds") }} --ignore-not-found;
              /opt/bitnami/kubectl/bin/kubectl delete secret {{ .Release.Name }}-ltpa-keys --ignore-not-found;
              /opt/bitnami/kubectl/bin/kubectl delete secret {{ .Release.Name }}-wlpadm --ignore-not-found;
              /opt/bitnami/kubectl/bin/kubectl delete secret {{ .Release.Name }}-hook-pullsecret --ignore-not-found
          {{- include "sch.security.securityContext" (list . .sch.chart.containerSecurityContext) | nindent 10 }}
          {{- include "initContainer.resources" . | nindent 10 }}
