{{- include "sch.config.init" (list . "apps.sch.chart.config.values") -}}
---
###############################################################################
# © Merative US L.P. 2022,2025
# Copyright 2019,2020 IBM Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
###############################################################################

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-transactions-cm
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "sch.metadata.labels.standard" (list . "") | nindent 4 }}
data:
  server_resources_tx.xml: |
    <?xml version="1.0" encoding="UTF-8"?>
    <!-- Placed by Kubernetes Configmap. -->
    <server description="Server Transaction Resource Configuration">

      <transaction
        clientInactivityTimeout="{{ .Values.sessionConfig.transactionTimeout }}"
        totalTranLifetimeTimeout="{{ .Values.sessionConfig.transactionTimeout }}"
        propogatedOrBMTTranLivetimeTimeout="{{ .Values.sessionConfig.transactionTimeout }}"
      />

    </server>
